import {
  gameAbbotMeeple,
  gameBeerBottle,
  gameClockwork,
  gameCrystalBars,
  gameFoldedPaper,
  gameHeartBottle,
  gameRoundPotion,
  gameShieldEchoes,
  gameStoneTablet,
} from '@ng-icons/game-icons';
import {
  tablerBible,
  tablerBlob,
  tablerBrain,
  tablerBubble,
  tablerCarrot,
  tablerCoins,
  tablerHeartBroken,
  tablerHelpHexagon,
  tablerShield,
  tablerSword,
  tablerSwords,
  tablerWall,
  tablerWood,
} from '@ng-icons/tabler-icons';

export function usedContentIcons(): Record<string, string> {
  return {
    tablerCoins,
    tablerSword,
    tablerHeartBroken,
    tablerBrain,
    tablerHelpHexagon,
    tablerBubble,
    tablerWood,
    tablerBlob,
    tablerCarrot,
    tablerBible,
    tablerWall,
    tablerShield,
    tablerSwords,
    gameRoundPotion,
    gameStoneTablet,
    gameFoldedPaper,
    gameShieldEchoes,
    gameAbbotMeeple,
    gameClockwork,
    gameHeartBottle,
    gameBeerBottle,
    gameCrystalBars,
  };
}
