import {
  gameAbbotMeeple,
  gameArrowFlights,
  gameAxeSwing,
  gameBeerBottle,
  gameBubbles,
  gameClockwork,
  gameCoinflip,
  gameCrystalBars,
  gameFoldedPaper,
  gameHealing,
  gameHeartBottle,
  gameRoundPotion,
  gameShieldEchoes,
  gameStoneSphere,
  gameStoneTablet,
  gameSwordClash,
  gameSwordWound,
  gameWaveStrike,
} from '@ng-icons/game-icons';
import {
  tablerBible,
  tablerBlob,
  tablerBrain,
  tablerBubble,
  tablerCarrot,
  tablerCoins,
  tablerHeartBroken,
  tablerHelpHexagon,
  tablerShield,
  tablerSword,
  tablerSwords,
  tablerWall,
  tablerWood,
} from '@ng-icons/tabler-icons';

export function usedContentIcons(): Record<string, string> {
  return {
    tablerCoins,
    tablerSword,
    tablerHeartBroken,
    tablerBrain,
    tablerHelpHexagon,
    tablerBubble,
    tablerWood,
    tablerBlob,
    tablerCarrot,
    tablerBible,
    tablerWall,
    tablerShield,
    tablerSwords,
    gameRoundPotion,
    gameStoneTablet,
    gameFoldedPaper,
    gameShieldEchoes,
    gameAbbotMeeple,
    gameClockwork,
    gameHeartBottle,
    gameBeerBottle,
    gameCrystalBars,
    gameHealing,
    gameWaveStrike,
    gameAxeSwing,
    gameCoinflip,
    gameBubbles,
    gameStoneSphere,
    gameArrowFlights,
    gameSwordClash,
    gameSwordWound,
  };
}
